FROM rust:latest

COPY Cargo.toml /Cargo.toml
COPY src/main.rs /src/main.rs

RUN apt update
RUN apt install -y gcc-arm-linux-gnueabihf
RUN rustup target add armv7-unknown-linux-gnueabihf
RUN cargo fetch

CMD "bash"
