FROM rust:latest

RUN apt update
RUN apt install -y gcc-arm-linux-gnueabihf pkg-config libssl-dev
RUN rustup target add armv7-unknown-linux-gnueabihf
RUN git clone https://github.com/tomaso/kouba_api.git
WORKDIR /kouba_api
RUN cargo build --target armv7-unknown-linux-gnueabihf --release
RUN rm /kouba_api/target/armv7-unknown-linux-gnueabihf/release/kouba_api

CMD "bash"
