FROM --platform=linux/arm/v7 rust:latest

COPY Cargo.toml /Cargo.toml
COPY src/main.rs /src/main.rs
COPY .cargo /.cargo

RUN apt update
RUN apt install -y gcc-arm-linux-gnueabihf
RUN rustup target add armv7-unknown-linux-gnueabihf
RUN cargo build --target armv7-unknown-linux-gnueabihf --release
RUN rm /target/armv7-unknown-linux-gnueabihf/release/kouba_api

CMD "bash"
