name: build_push_builder_image_for_armv7

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push for alpine
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.build.armv7
          tags: ghcr.io/tomaso/kouba_api:builder-for-armv7
          push: true
